/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.korvin;

import org.apache.commons.lang3.StringUtils;

public class App {
    public String getGreeting() {
        return StringUtils.upperCase("hello world and sascha!");

    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
