/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.korvin;


public class AppTest {
//    @Test
//    public void appHasAGreeting() {
//        String greeting = "hello";
//        assertNotNull(greeting);
//    }
}
